### PR TITLE
README.md: Use markdown for bookmarklet links

### PR DESCRIPTION
**Pull request by Stevoisiak**

### CODE REVIEW

**Comment by FarhadG** [comment]
Thanks for the update. Please add your name to the `contributors` list in the repo and I'll merge this into `maser`

**Comment by Stevoisiak** [comment]
@FarhadG Would you like me to amend my last commit, or will you be squash-merging?

**Comment by FarhadG** [comment]
Whichever's fine by me. Thanks for asking.

**Comment by Stevoisiak** [comment]
@FarhadG As requested, I have added my name to the contributors list.

**Pull request merged**
