### PR TITLE
void 0

### PR DESCRIPTION
**Pull request by ghost**
The bookmarklet needs a

~~~
void 0
~~~

on the end else it fails

### CODE REVIEW

**Comment by FarhadG** [comment]
Thanks for opening the issue, @svnpenn. Can you please elaborate what you mean? What breaks and what needs this additional `void 0`? Thank you!

**Comment by ghost** [comment]
void 0 prevents the bookmarklet from redirecting the page, else you are left with

~~~
[object Promise]
~~~

for goodness sake, it even says it on wikipedia

http://wikipedia.org/wiki/Bookmarklet#Concept

**Comment by FarhadG** [comment]
Ha, thanks for the link. It makes sense... it wasn't doing that in my browser but can see why it's needed in our case.

For goodness sake, can you open a PR, @svnpenn ? :)

**Comment by ghost** [comment]
@FarhadG done

**Comment by FarhadG** [comment]
Great! Thanks, @svnpenn !

**Comment by svnpenn** [comment]
@FarhadG thanks - how do we get it pushed to the live site?

**Comment by ghost** [comment]
@FarhadG it looks like I missed `landing/index.html` - do you need me to send another PR or can you get it?

**Comment by FarhadG** [comment]
Oh, good catch, @svnpenn! You should just run the `build` script as a previous PR was put in to be generate that for us. Thanks for improving this for everyone.

**Comment by ghost** [comment]
@FarhadG why do you have the same files on both branches? See:

- http://github.com/FarhadG/init/blob/master/landing/index.html
- http://github.com/FarhadG/init/blob/gh-pages/landing/index.html

and:

- http://github.com/FarhadG/init/blob/master/src/index.js
- http://github.com/FarhadG/init/blob/gh-pages/src/index.js

and which branch are you using as the source for the GitHub Pages site?

**Comment by FarhadG** [comment]
@svnpenn , it's because the `master` branch is what's used for development and `gh-pages` is the same thing but the one that github pages tracks for the static site. Last time I checked, you needed the `gh-pages` branch for the static sites. I assume it's still the case.

**Comment by ghost** [comment]
@FarhadG you do not need both. You can do:

1. Just the gh-pages branch, see http://github.com/svnpenn/bm

2. Just the master branch

3. Just the `docs` folder of the master branch, see
   http://github.com/svnpenn/rosso

**Comment by FarhadG** [comment]
Awesome! It's been some time since I've looked at what they do now. Good to know. Thanks for the info, @svnpenn . Feel free to open a PR and I'll merge -- I like the `demo` version.

**Pull request merged**
